### ISSUE TITLE
Can't connect to Rizon

### ISSUE THREAD

**Issue by YamashitaRen** [areeb-beigh/RSS2IRC#5] opened 2017-01-22 15:17 UTC
```
$ python3 rss2irc.py

    ---------------------------------------------
    RSS2IRC Bot by Areeb - github.com/areebbeigh
    ---------------------------------------------
    
Attempting to identify...
b'PRIVMSG NickServ :IDENTIFY [RSS]Cassandre MyPassword\r\n'

line: [':irc.uworld.se', 'NOTICE', '*', ':***', "Couldn't", 'look', 'up', 'your', 'hostname', '(cached)']
line: [':irc.uworld.se', 'NOTICE', '*', ':***', 'Checking', 'Ident']
line: [':irc.uworld.se', 'NOTICE', '*', ':***', 'No', 'Ident', 'response']
line: ['PING', ':1254255970']
line: [':irc.uworld.se', '451', '[RSS]Cassandre', ':You', 'have', 'not', 'registered']
line: [':irc.uworld.se', '451', '[RSS]Cassandre', ':You', 'have', 'not', 'registered']
line: [':irc.uworld.se', '451', '[RSS]Cassandre', ':You', 'have', 'not', 'registered']

line: [':irc.uworld.se', '451', '[RSS]Cassandre', ':You', 'have', 'not', 'registered']
```

Then the console goes blank.
No issue on Freenode.

**Comment by areebbeigh** [comment] 2017-01-23 05:27
Can you tell me the channel you're trying to get the bot to join? Because it might be the channel mode. For example if a channel mode is +R then non-registered users can't join it. Haven't tried connecting to Rizon yet though.

**Comment by YamashitaRen** [comment] 2017-01-23 13:59
The channel is #Genshiken (+znt). It's a public channel so I doubt it has anything to do with the issue...

**Comment by areebbeigh** [comment] 2017-01-23 18:36
Alright, the issue is fixed now. Turns out the bot was not replying to CTCP PING requests. Please note that the bot may take up to 60 seconds before it starts joining channels on networks like Rizon now. Feel free to open an issue if you face any trouble again.

**Closed as completed by areebbeigh** 2017-01-23 18:36 UTC
Labels: bug

**Comment by pwsincd** [comment] 2017-02-09 20:24
hi can you help ... 

i fell i have everything set right , howver i get these errors...

    ---------------------------------------------
    RSS2IRC Bot by Areeb - github.com/areebbeigh
    ---------------------------------------------

Traceback (most recent call last):
  File "rss2irc.py", line 268, in <module>
    main()
  File "rss2irc.py", line 56, in main
    irc.connect()
  File "rss2irc.py", line 72, in connect
    self.s.send(bytes("NICK %s\r\n" % NICK, "UTF-8"))
TypeError: str() takes at most 1 argument (2 given)

**Comment by YamashitaRen** [comment] 2017-02-09 20:25
I think you have to use python3.

**Comment by pwsincd** [comment] 2017-02-09 20:26
oh really ?  damn..  anyone aware of a decent python rss feed bot for 2.7
